baseURL = 'https://hammitopurple.github.io'
languageCode = 'en-us'
title = 'Achieve Grapeness'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'

# add an about page i guess
[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 1
